config/routes.rb
require 'resque/server'
Copper::Application.routes.draw do
  resources :tips, except:[:edit]
  resources :checks, only:[:index, :show]

  resources :orders, only:[:index, :show] do
    resources :tips, only:[:index]
  end

  resources :authors, only:[:index, :show, :update, :destroy] do
    resources :pages, only:[:index]
  end

  resources :pages, only:[:index, :show, :update] do
    resources :tips, only:[:index]
    member do
       put 'reject'
     end
  end

  resources :users, only:[:index, :update, :show] do
    resources :tips, only:[:index]
    resources :authors, only:[:index]
    resources :pages, only:[:index]
    resources :orders, only:[:index]
    resources :checks, only:[:index]
  end

  get    'cards', to:'cards#show',   :as => :show_card
  post   'cards', to:'cards#create', :as => :create_card
  put    'cards', to:'cards#update', :as => :update_card
  delete 'cards', to:'cards#delete', :as => :delete_card

  get 'tip_some_pages',       to:'home#tip_some_pages'
  get "integrations",         to:'home#integrations'
  get 'badge',                to:'home#badge'
  get 'author',               to:'home#author'
  get 'settings',             to:'home#settings'
  get 'about',                to:'home#about'
  get 'getting_started',      to:'home#getting_started'
  get 'tipped',               to:'home#tipped'
  get 'contact',              to:'home#contact'
  get 'terms',                to:'home#terms'
  get 'privacy',              to:'home#privacy'
  get 'faq',                  to:'home#faq'
  get 'states',               to:'home#states'
  get 'ping',                 to:'home#ping'
  get 'embed_iframe.js',      to:'home#iframe', :as => :iframe

  post '/claim_facebook_pages',      to:'home#claim_facebook_pages'

  if Rails.env.test? || Rails.env.development? || Rails.env.staging?
    get 'test',    to:'home#test'
  end

  match "/signout" => "sessions#destroy", :as => :signout
  match "/signin" => "sessions#new", :as => :signin
  match "/auth/:provider/callback" => "sessions#create", :as => :provider_callback
  match '/auth/failure'  => 'sessions#failure'
  match '/auth/facebook/setup', :to => 'sessions#facebook_setup'
  match '/auth/facebook/publish_actions', :to => 'sessions#publish_actions'
  match '/auth/facebook/manage_pages', :to => 'sessions#manage_pages'

  mount Resque::Server.new, :at => "/admin/resque"
  root :to => 'home#index'

  # constraints allow usernames to have periods
  get "/:provider/:username",  to:'authors#enquire', constraints:{username:/[^\/]+/}

end

app/models/user.rb
class User < ActiveRecord::Base
  include Enqueueable
  include UserMessages
  has_many :authors
  has_many :orders
  has_many :tips, :through => :orders
  has_many :pages, :through => :tips, :order => "tips.created_at DESC"
  has_many :checks
  has_and_belongs_to_many :roles
  has_paper_trail

  attr_accessible :name, :email, :tip_preference_in_cents,
    :accept_terms, :payable_to, :line1, :line2, :city, :postal_code,
    :country_code, :subregion_code, :share_on_facebook

  scope :tipped, joins(:tips)
  scope :payment_info, where('stripe_id IS NOT NULL')

  validates :tip_preference_in_cents,
    :numericality => { greater_than_or_equal_to:Tip::MINIMUM_TIP_VALUE },
    :presence => true
  validates :name, length:{in:3..128}, allow_nil:true

  EMAIL_RE = /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates :email, format:{with:EMAIL_RE}, :allow_nil => true

  validate :validate_one_current_order, on:'save'
  def validate_one_current_order
    errors.add(:orders, "there must be only one") unless self.orders.current.size == 1
  end

  after_create do
    create_current_order!
    Resque.enqueue User, self.id, :send_welcome_message
  end

  def create_current_order!
    if self.orders.unpaid.count > 0
      raise "there is already an unpaid Order for this user: #{self.inspect}"
    end
    self.orders.create!
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.roles << Role.find_by_name('fan')
    end
  end

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def paid_royalties
    Tip.kinged.where(page_id:authored_pages.pluck(:id))
  end

  def pending_royalties
    Tip.charged.where(page_id:authored_pages.pluck(:id))
  end

  def royalties
    Tip.where(page_id:authored_pages.pluck(:id))
  end

  def average_royalties
    royalties = Tip.where(page_id:authored_pages.pluck(:id)).average(:amount_in_cents)
    royalties = 0 unless royalties
    royalties.round
  end

  def authored_pages
    Page.where(author_id: author_ids).includes(:tips)
  end

  def tipped_pages
    pages.group('pages.id').includes(:tips).except(:order).order('MAX(tips.created_at) DESC')
  end


  def tip(args = {})
    url    = args[:url]
    amount_in_cents = args[:amount_in_cents] || self.tip_preference_in_cents
    title  = CGI.unescapeHTML(args[:title])  if args[:title]

    tip = current_order.tips.build(amount_in_cents:amount_in_cents)
    unless tip.page = Page.find_by_url(url)
      tip.page = Page.create(url:url,title:title)
    end
    tip.save!
    Resque.enqueue Tip, tip.id, :see_about_facebook_feed
    tip
  end

  def current_order
    self.orders.current.first or self.orders.create
  end

  # def try_to_create_check!
  #   the_tips = []
  #   self.authors.each do |ident|
  #     the_tips += ident.tips.charged.all
  #   end
  #   unless the_tips.empty?
  #     if check = self.checks.create
  #       the_tips.each do |tip|
  #         check.tips << tip
  #         tip.claim!
  #         tip.save!
  #       end
  #       check.save!
  #     end
  #   end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  filter_access_to :all
  filter_access_to :update, attribute_check:true
  def index
    @users = User.order("created_at DESC").endless(params[:endless])
    render :action => 'index', :layout => false if request.headers['retrieve_as_data'] or params[:endless]
  end

  def update
    if 'me' == params[:id]
      @user = current_user
    else
      @user = User.find(params[:id])
    end

    @user.update_attributes(params[:user])
    @user.tip_preference_in_cents = params[:tip_preference_in_cents] if params[:tip_preference_in_cents]
    @user.email = params[:email] if params[:email]
    @user.save!
    render nothing:true, status:200
  end

  def show
    if params[:id] == 'me'
      @user = current_user
    else
      @user = User.find(params[:id])
    end
    render :action => 'show', :layout => false if request.headers['retrieve_as_data']
  end
end

app/views/users/_form.html.erb
<section>
  <style>
    @import url("/users/design.css");
  </style>
  <script src="/users/behavior.js"></script>
  <h1>Setting things up</h1>
  <p>
    Configure your account by clicking on each section.
  </p>
  <div id="bookmarklet"  class="required">
    <summary>
      Install the bookmarklet
    </summary>
    <p>
      Drag bookmarklet to your browser toolbar.
    </p>
    <p>
      <span>&#x27A0;</span>
      <a id="dirtywhitecouch" href="<%= render :partial => 'tips/wrapped_launcher.js' %>" tabindex="1" accesskey="p">Tip</a>
    </p>
  </div>
  <div id="tip_rate" >
    <summary>Select your tip rate</summary>
    <p>
      Select the amount you want each tip to be.
    </p>
    <form action="" method="post" accept-charset="utf-8">
      <input name="_method" type="hidden" value="put">
      <input name="authenticity_token" type="hidden" value="<%=form_authenticity_token%>">
      <fieldset>
        <label for="user_tip_preference_in_cents">Tip Rate</label>
        <select name="user[tip_preference_in_cents]" id="user_tip_preference_in_cents">
          <option value="5">$0.05</option>
          <option value="10">$0.10</option>
          <option value="25">$0.25</option>
          <option value="50">$0.50</option>
          <option value="75">$0.75</option>
          <option value="100">$1.00</option>
          <option value="200">$2.00</option>
          <option value="300">$3.00</option>
          <option value="500">$5.00</option>
        </select>
      </fieldset>
    </form>
  </div>

</section>

app/views/users/_index.html.erb
<%-cache user do-%>
<details itemscope itemtype='user' itemid='/users/<%=user.id%>'>
  <summary><%=user.name%></summary>
</details>
<%-end-%>

app/views/users/_model.html.erb
<%-cache user do-%>
<dl itemscope itemtype='user' itemid='<%=user_url(user)%>'>
  <dd itemprop="id"><%=user.id%></dd>
  <dd itemprop='name'><%=user.name%></dd>
  <dd itemprop="email"><%=user.email%></dd>
  <dd itemprop="tip_preference_in_cents"><%=user.tip_preference_in_cents%></dd>
  <dd itemprop="tip_count"><%=user.tips.count%></dd>
  <dd itemprop="stripe_id"><%=user.stripe_id%></dd>
  <dd itemprop='accept_terms'><%=user.accept_terms%></dd>
  <dd itemprop='share_on_facebook'><%=user.share_on_facebook%></dd>
  <dd itemprop="created_at"><%=user.created_at.getutc.iso8601%></dd>
  <dd itemprop="updated_at"><%=user.updated_at.getutc.iso8601%></dd>
  <%-user.roles.each do |role| -%>
  <dd itemprop="<%=role.name%>">true</dd>
  <%-end-%>
</dl>
<%-end-%>

app/views/users/_show.html.erb
<%-cache user do-%>
<section>
  <header></header>
  <dl>
    <dt>ID</dt>
    <dd itemprop="id"><%=user.id%></dd>
    <dt>Created</dt>
    <dd itemprop="created_at"><time itemprop="created_at" datetime="<%=user.created_at.getutc.iso8601%>"/></dd>
    <dt>updated</dt>
    <dd><time itemprop="updated_at" datetime="<%=user.updated_at.getutc.iso8601%>"/></dd>
    <dt>name</dt>
    <dd itemprop='name'><%=user.name%></dd>
    <dt>email</dt>
    <dd itemprop="email"><%=user.email%></dd>
    <dt>tip preference</dt>
    <dd itemprop="tip_preference_in_cents"><%=user.tip_preference_in_cents%></dd>
    <dt>stripe id</dt>
    <dd itemprop="stripe_id">
      <a target="_blank" href="https://manage.stripe.com/customers/<%=user.stripe_id%>"><%=user.stripe_id%></a>
    </dd>
    <dt>accepts terms</dt>
    <dd itemprop='accept_terms'><%=user.accept_terms?%></dd>
    <dt>facebook sharing</dt>
    <dd itemprop='share_on_facebook'><%=user.share_on_facebook?%></dd>
  </dl>
  <footer>
    <details>
      <summary>address</summary>
      <section>
        <dl>
          <dt>payable to</dt>
          <dd itemprop="payable_to"><%=user.payable_to%></dd>
          <dt>line1</dt>
          <dd itemprop="line1"><%=user.line1%></dd>
          <dt>line2</dt>
          <dd itemprop="line1"><%=user.line2%></dd>
          <dt>city</dt>
          <dd itemprop="city"><%=user.city%></dd>
          <dt>state</dt>
          <dd itemprop="subregion_code"><%=user.subregion_code%></dd>
          <dt>zip</dt>
          <dd itemprop="postal_code"><%=user.postal_code%></dd>
          <dt>country</dt>
          <dd itemprop="country_code"><%=user.country_code%></dd>
        </dl>
      </section>
    </details>
    <details itemscope itemtype='tip' itemid='/users/<%=user.id%>/tips'>
      <summary>tips</summary>
    </details>
    <details itemscope itemtype='author' itemid='/users/<%=user.id%>/authors'>
      <summary>authors</summary>
    </details>
    <details itemscope itemtype='order' itemid='/users/<%=user.id%>/orders'>
      <summary>orders</summary>
    </details>
    <details itemscope itemtype='check' itemid='/users/<%=user.id%>/checks'>
      <summary>checks</summary>
    </details>
  </footer>
</section>
<%-end-%>

app/views/users/edit.html.erb
<%-content_for :head do-%>
  <title><%=current_user.name%>'s Settings - Copper.</title>
<%-end-%>
<section id="banner">
  <header>
    <%= image_tag "icons/silhouette.svg", class:"identity", alt:'me' %>
  </header>
  <hgroup>
    <h1>Your Settings</h1>
    <p><%=current_user.name%><a href="/signout">not you?</a></p>
  </hgroup>
  <p>
    Hey, cool. You’ve found some great stuff to tip with Copper.
    Let’s get your tips to the creators...
    <br><br>
    Please add your payment info so we can start getting your 
    tips to the people whose content you’ve liked. Once we have 
    your info we’ll charge you monthly whenever you have over 
    $10 of tips pledged.
  </p>
</section>
<section id="email" class="setting">
  <header>
    <h2>Contact Info</h2>
    <a href="#">Change</a>
  </header>
  <div>
    <h4>Email Address</h4>
    <p itemprop="email"><%=current_user.email%></p>
  </div>
  <form method="put" action="/fans/me" accept-charset="UTF-8">
    <input itemprop="email" name='user[email]' type="email" required value="<%=current_user.email%>">
    <input type="submit" value="Save"/>
  </form>
</section>
<section id="rate" class="setting">
  <header>
    <h2>Default Tip</h2>
    <a href="#">Change</a>
  </header>
  <div>
    <p itemprop="tip_preference_in_cents"><%=current_user.tip_preference_in_cents%></p>
  </div>
  <form method="put" action="/fans/me" accept-charset="UTF-8">
    <select itemprop="tip_preference_in_cents" name="user[tip_preference_in_cents]">
      <option value="5" <%= 'selected ' if current_user.tip_preference_in_cents == 5%> >$0.05</option>
      <option value="10" <%= 'selected ' if current_user.tip_preference_in_cents == 10%>>$0.10</option>
      <option value="25" <%= 'selected ' if current_user.tip_preference_in_cents == 25%>>$0.25</option>
      <option value="50" <%= 'selected ' if current_user.tip_preference_in_cents == 50%>>$0.50</option>
      <option value="75" <%= 'selected ' if current_user.tip_preference_in_cents == 75%>>$0.75</option>
      <option value="100" <%= 'selected ' if current_user.tip_preference_in_cents == 100%>>$1.00</option>
      <option value="200"<%= 'selected ' if current_user.tip_preference_in_cents == 200%>>$2.00</option>
      <option value="300" <%= 'selected ' if current_user.tip_preference_in_cents == 300%>>$3.00</option>
      <option value="500" <%= 'selected ' if current_user.tip_preference_in_cents == 500%>>$5.00</option>
      <option value="1000" <%= 'selected ' if current_user.tip_preference_in_cents == 1000%>>$10.00</option>
      <option value="1500" <%= 'selected ' if current_user.tip_preference_in_cents == 1500%>>$15.00</option>
      <option value="2000" <%= 'selected ' if current_user.tip_preference_in_cents == 2000%>>$20.00</option>
    </select>
    <input type="submit" value="Save"/>
  </form>
</section>
<section id="card" class="setting">
  <header>
    <h2>Payment Info</h2>
    <a href="#">Change</a>
  </header>
  <div>
    <section>
      <h4>Type Of Card</h4>
      <p class="type"></p>
    </section>
    <section>
      <h4>Card Number</h4>
      <p class="number"></p>
    </section>
    <section>
      <h4>Expiration</h4>
      <p class="expiration"></p>
    </section>
  </div>
  <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
  <input itemprop="stripe_id" name="stripe_id" type="hidden" value="<%=current_user.stripe_id%>">
  <form method="put">
    <!-- 4242424242424242 test approved-->
    <!-- 4000000000000002 test declined-->
    <h1></h1>
    <fieldset>
      <input type="text" autocomplete="off" id="number" placeholder="Card Number" required />
      <input type="text" autocomplete="off" id="cvc" placeholder="CVC"  required />
    </fieldset>
    <fieldset>
      <select id="month">
        <option value="1">January</option>
        <option value="2">February</option>
        <option value="3">March</option>
        <option value="4">April</option>
        <option value="5">May</option>
        <option value="6">June</option>
        <option value="7">July</option>
        <option value="8">August</option>
        <option value="9">September</option>
        <option value="10">October</option>
        <option value="11">November</option>
        <option value="12">December</option>
      </select>
      <select id="year">
        <option value="2012">2012</option>
        <option value="2013">2013</option>
        <option value="2014">2014</option>
        <option value="2015">2015</option>
        <option value="2016">2016</option>
        <option value="2017">2017</option>
        <option value="2018">2018</option>
        <option value="2019">2019</option>
        <option value="2020">2020</option>
        <option value="2021">2021</option>
      </select>
    </fieldset>
    <fieldset class="pay">
      <input itemprop="accept_terms" type="checkbox"  name="user[accept_terms]" id="site_terms" value="true" <%= "checked" if current_user.accept_terms? %> />
      <label for="site_terms">I accept the <a href="/terms" target="window">terms</a></label>
    </fieldset>
    <input type="submit" value="Save" />
  </form>
</section>
<nav>
  <a href="/fans/me">return to profile</a>
</nav>

app/views/users/index.html.erb
<%= render partial:"index", collection:@users, as: :user %>

app/views/users/show.html.erb
<%= render partial:"show", object: @user, as: :user %>