config/routes.rb
require 'resque/server'
Copper::Application.routes.draw do
  resources :tips, except:[:edit]
  resources :checks, only:[:index, :show]

  resources :orders, only:[:index, :show] do
    resources :tips, only:[:index]
  end

  resources :authors, only:[:index, :show, :update, :destroy] do
    resources :pages, only:[:index]
  end

  resources :pages, only:[:index, :show, :update] do
    resources :tips, only:[:index]
    member do
       put 'reject'
     end
  end

  resources :users, only:[:index, :update, :show] do
    resources :tips, only:[:index]
    resources :authors, only:[:index]
    resources :pages, only:[:index]
    resources :orders, only:[:index]
    resources :checks, only:[:index]
  end

  get    'cards', to:'cards#show',   :as => :show_card
  post   'cards', to:'cards#create', :as => :create_card
  put    'cards', to:'cards#update', :as => :update_card
  delete 'cards', to:'cards#delete', :as => :delete_card

  get 'tip_some_pages',       to:'home#tip_some_pages'
  get "integrations",         to:'home#integrations'
  get 'badge',                to:'home#badge'
  get 'author',               to:'home#author'
  get 'settings',             to:'home#settings'
  get 'about',                to:'home#about'
  get 'getting_started',      to:'home#getting_started'
  get 'tipped',               to:'home#tipped'
  get 'contact',              to:'home#contact'
  get 'terms',                to:'home#terms'
  get 'privacy',              to:'home#privacy'
  get 'faq',                  to:'home#faq'
  get 'states',               to:'home#states'
  get 'ping',                 to:'home#ping'
  get 'embed_iframe.js',      to:'home#iframe', :as => :iframe

  post '/claim_facebook_pages',      to:'home#claim_facebook_pages'

  if Rails.env.test? || Rails.env.development? || Rails.env.staging?
    get 'test',    to:'home#test'
  end

  match "/signout" => "sessions#destroy", :as => :signout
  match "/signin" => "sessions#new", :as => :signin
  match "/auth/:provider/callback" => "sessions#create", :as => :provider_callback
  match '/auth/failure'  => 'sessions#failure'
  match '/auth/facebook/setup', :to => 'sessions#facebook_setup'
  match '/auth/facebook/publish_actions', :to => 'sessions#publish_actions'
  match '/auth/facebook/manage_pages', :to => 'sessions#manage_pages'

  mount Resque::Server.new, :at => "/admin/resque"
  root :to => 'home#index'

  # constraints allow usernames to have periods
  get "/:provider/:username",  to:'authors#enquire', constraints:{username:/[^\/]+/}

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  filter_access_to :author, :require => :read
  filter_access_to :settings, :require => :read
  filter_access_to :claim_facebook_pages, :require => :read
  filter_access_to :integrations, :require => :manage
  respond_to :html

  def index
    unless current_user
      redirect_to :action => 'tipped', :status => 302
    end
  end

  def author
  end

  def settings
  end

  def getting_started
  end

  def badge
  end

  def tip_some_pages
  end

  def integrations
  end

  def tipped
    response.headers['Cache-Control'] = 'public, max-age=300'
  end

  def about
    response.headers['Cache-Control'] = 'public, max-age=300'
  end

  def faq
    response.headers['Cache-Control'] = 'public, max-age=300'
  end

  def privacy
    response.headers['Cache-Control'] = 'public, max-age=300'
  end

  def terms
    response.headers['Cache-Control'] = 'public, max-age=300'
  end

  def contact
    response.headers['Cache-Control'] = 'public, max-age=300'
  end

  def iframe
    response.headers['Cache-Control'] = 'public, max-age=300'
    render :action => 'embed_iframe', :format => [:js], :layout => false
  end

  def test
    render :action => 'test', :layout => false
  end

  def states
    @country = Country.coded(params['country_code'])
    if @country.subregions?
      render :action => 'states', :layout => false
    else
      render nothing:true, status:200
    end
  end

  def claim_facebook_pages
    if pages = params[:facebook_objects]

      facebook = Author.where(provider:"facebook", user_id:current_user.id).first
      graph = Koala::Facebook::API.new(facebook.token)

      puts "getting facebook pages owned by author #{current_user.name}"
      pages.each  do |id|
        puts id
        fb_page =  graph.get_object(id)
        another_me = Author.find_or_create_from_url(fb_page['link'])

        another_me.user = current_user
        another_me.join!
      end
    end
    render nothing:true, status:200
  end

  def ping
    Page.count
    render action:'ping', layout:false
  end

end

app/views/home/about.html.erb
<%-cache do-%>
<%-content_for :head do-%>
  <title>About Us - Copper.</title>
<%-end-%>
<section id="about_us">
  <article>
    <h1>About Us</h1>
    <p>
      We're a team of people that want to pay people for doing
      their jobs - and <a href="/how">the way</a>
      we're doing this is by making it easy to tip.
    </p>
    <p>
      We support the "free" internet and the people that make it, we
      also know that bills need to get paid and that tips are always
      appreciated.
    </p>

    <p>
      It is our hope you will join us (as a Fan) to pay those who
      are creating worthy content (Authors). Whether it’s five cents
      or five dollars, it's our job to connect you to these Authors
      no matter what the work - the only requirement is they have a
      web page and a bank account.
    </p>
  </article>
</section>
<%-end-%>

app/views/home/author.html.erb
<%-cache current_user do-%>
  <section id="banner">
    <header>
      <a href=/><img src="<%=current_user.authors.first.profile_image%>" class="author"></a>
    </header>
    <hgroup>
      <h1>Your pages</h1>
      <p><%=@current_user.name%><a href="/signout">not you?</a></p>
    </hgroup>
    <p>
      Hi <%=@current_user.name%>! On this page,
      you can see what content your fans are connecting with
      and the tips they’ve sent to show their appreciation.
    </p>
  </section>

  <section id="stats" >
    <header>
    </header>
    <div>
      <h2>Tip count</h2>
      <p><%=current_user.royalties.count%></p>
    </div>
    <div>
      <h2>Tips Paid</h2>
      <p data-cents="<%=current_user.paid_royalties.count%>"></p>
    </div>
    <div>
      <h2>Tips pending</h2>
      <p data-cents="<%=current_user.pending_royalties.sum :amount_in_cents%>"></p>
    </div>
    <div>
      <h2>highest tip</h2>
        <p data-cents="<%=current_user.royalties.maximum :amount_in_cents%>"></p>
    </div>
    <div>
      <h2>Average tip</h2>
      <p data-cents="<%=current_user.average_royalties%>"></p>
    </div>
    <div>
      <h2>Total tips</h2>
      <p data-cents="<%=current_user.royalties.sum :amount_in_cents %>"></p>
    </div>
  </section>

  <section id="services" itemscope itemtype="user" itemid="/users/<%=current_user.id%>">
    <details>
      <summary>Authorize services</summary>
      <section>
        <div>
          <%-current_user.authors.each do |author|-%>
          <figure class="<%=author.provider%>" itemscope itemtype="author"  itemid="/authors/<%=author.id%>">
            <%= image_tag "providers/#{author.provider}/sign_in.png", title:author.username%>
            <%-if author.username-%>
              <figcaption itemprop='username'><%=author.username%></figcaption>
            <%-else-%>
              <figcaption itemprop='uid'><%=author.uid%></figcaption>
            <%-end-%>
            <%-if current_user.authors.count > 1-%>
            <form action='<%=author_path(author)%>' method="delete">
              <input type="submit" name="submit" value="X">
            </form>
            <%-end-%>
          </figure>
          <%-end-%>
        </div>
        <aside>
          <header>
            <h2>Authorize other services</h2>
          </header>
          <nav>
            <a href="/auth/facebook" title="Authorize facebook">
              <%= image_tag "providers/facebook/sign_in.png"%>
            </a>
            <a href="/auth/twitter" title="Authorize twitter">
              <%= image_tag "providers/twitter/sign_in.png"%>
            </a>
            <a href="/auth/google_oauth2" title="Authorize google">
              <%= image_tag "providers/google/sign_in.png"%>
            </a>
            <a href="/auth/soundcloud" title="Authorize soundcloud">
              <%= image_tag "providers/soundcloud/sign_in.png"%>
            </a>
            <a href="/auth/vimeo" title="Authorize vimeo">
              <%= image_tag "providers/vimeo/sign_in.png"%>
            </a>
            <a href="/auth/tumblr" title="Authorize tumblr">
              <%= image_tag "providers/tumblr/sign_in.png"%>
            </a>
            <a href="/auth/github" title="Authorize github">
              <%= image_tag "providers/github/sign_in.png"%>
            </a>
            <a href="/auth/flickr" title="Authorize flickr">
              <%= image_tag "providers/flickr/sign_in.png"%>
            </a>
          </nav>
          <%-current_user.authors.each do |author|-%>
            <%-if author.provider == 'facebook' and author.token -%>
              <a href="/auth/facebook/manage_pages">Claim facebook pages</a>
            <%-end-%>
          <%-end-%>
        </aside>
      </section>
    </details>
    <aside id='facebook_pages'>
      <header>
        <h2>Facebook pages you admin</h2>
        <p class='help'>check all the pages you want to recieve tips for</p>
      </header>
      <form method="post" action='/claim_facebook_pages'>
        <fieldset>
        </fieldset>
        <input type='submit' value="Claim paiges">
      </form>
    </aside>
  </section>

  <section class="pages" >
    <%= render partial:"pages/author_details", collection:current_user.authored_pages, as: :page %>
  </section>
  <nav>
    <a href="/settings">Edit your settings</a>
  </nav>
  <%-end-%>

app/views/home/authors.html.erb
<% content_for :head do %>
  <title>Information for Authors - copper.is</title>
  <%= javascript_include_tag "home/authors" %>
<% end %>

<section id="authors">
  <h1>Author settings</h1>

  <section id="identity">
    <header>
      <h2>Identities <span><%= current_user.identities.count%></span></h2>
      <p>Link the sites you have content on.</p>
    </header>
    <a href="/users/current/identities">edit</a>
  </section>
  <section id="badge">
    <header>
      <h2>Badge</h2>
      <p>
        Invite Fans to tip you for your work and help spread the
        word by including our badge on pages you've created.
      </p>
    </header>
    <form>
      <input type="hidden" name="type" value="name" id="type"/>

      <label for="color">Color</label>
      <select name="color" id="color" size="1">
        <option value="copper">copper</option>
        <option value="black">black</option>
      </select>

      <label for="size">Size</label>
      <select name="size" id="size" size="1">
        <option value="25">25px</option>
        <option value="40">40px</option>
        <option value="50">50px</option>
        <option value="75">75px</option>
        <option value="100">100px</option>
        <option value="150">150px</option>
        <option value="200"  selected>200px</option>
        <option value="250">250px</option>
        <option value="300">300px</option>
      </select>

    </form>
    <aside>
      <textarea name="badge_text" id="badge_text"></textarea>
      <figure></figure>
      <script id="badge_template" type="text/x-jquery-tmpl">
        <img class="copper_badge" src="<%=request.scheme%>://<%=request.host%>:<%=request.port%>/assets/logo/${type}/${color}.png"
             style="cursor:pointer; width:${size}px;" title="Pay this author for their work"
             onclick="<%= render :partial=>'tips/wrapped_launcher', :formats=>[:js] %>">
      </script>
    </aside>
    <p>
      First select the kind of badge you want. Then copy the contents
      of the text are into your clipboard. You can then paste the
      code into any pages you'd like to see tipped.
    </p>
  </section>
  <section id="link"></section>
</section>

app/views/home/badge.html.erb
<section id="banner">
  <header>
    <a href=/><%= image_tag "icons/silhouette.svg", class:"author", alt:'me' %></a>
  </header>
  <hgroup>
    <h1>Get the badge</h1>
  </hgroup>
  <p>
    Select the size badge you want on your page. Then copy the code and 
    paste it alongside content you create.
  </p>
</section>

<section id="badge">
  <div>
    <header>
      <h3>Get the badge</h3>
      <p>
        Place this on your site to drive tips to your work! Select a size.
      </p>
      <select name="size" id="size" size="1">
        <option value="" disabled selected>Select Size</option>
        <option value="100">Small</option>
        <option value="145">Medium</option>
        <option value="175">large</option>
      </select>
    </header>
    <figure></figure>
  </div>
  <div>
    <header>
      <h3>Embed code</h3>
    </header>
    <textarea name=""></textarea>
  </div>
  <script id="badge_template" type="text/x-jquery-tmpl">
    <img id="copper_badge" src="<%=request.scheme%>://<%=request.host%>:<%=request.port%>/assets/icons/button.png"
         style="cursor:pointer; width:${size}px;" title="Tip This Page"
         onclick="<%= render :partial=>'home/wrapped_launcher', :formats=>[:js] %>">
  </script>
</section>

app/views/home/embed_iframe.js.erb
<%-cache do-%>
(function(){
  var f = document.getElementById('copper_tip');
  window.addEventListener('message', function(event) {

    var data = event.data
    if (data.type == 'show'){
      // console.debug("show")
      f.width='425px'
      f.height='575px'
    }
    else if (data.type == 'show_details'){
      // console.debug("show_details")
      f.width='550px'
      f.height='475px'
    }
    else if (data.type == 'hide'){
      // console.debug("hide")
      f.width='350px'
      f.height='0px'
    }
    else if(data.type == 'gather_page_info'){
      var page_title, page_url;
      if(document.querySelector('meta[property="og:title"]'))
        page_title = document.querySelector('meta[property="og:title"]').getAttribute('content');
      else if(document.querySelector('title'))
        page_title=document.querySelector('title').innerHTML
      else
        page_title=""

      if (document.querySelector('link[rel="canonical"]'))
        page_url = document.querySelector('link[rel="canonical"]').getAttribute('href');
      else if (document.querySelector('meta[property="og:url"]'))
        page_url = document.querySelector('meta[property="og:url"]').getAttribute('content');
      else
        page_url = window.location
      var message = {
        type:"tip_info",
        url:encodeURIComponent(page_url),
        title:encodeURIComponent(page_title)
      }
      event.source.postMessage(message, "*");
    }
  }, false);

  if (f) {
    f.contentWindow.postMessage({type:"tip_display"}, "*");
  }
  else {
    f=document.createElement('iframe');
    f.id='copper_tip';
    f.name='copper';
    f.style.position='fixed';
    f.style.top='0';
    f.style.left='40%';
    f.style.padding='0';
    f.style.margin='0 auto';
    f.scrolling='no';
    f.frameborder=0;
    f.style.background.color='transparent';
    f.style.border='none';
    f.allowtransparency='allowtransparency';
    f.src='<%=request.scheme%>://<%=request.host%>:<%=request.port%>/tips/new'
    document.body.appendChild(f);
    f.width='0';
    f.height='0';
    f.style.zIndex='9999999999999999';
  }
})()
<%-end-%>

app/views/home/getting_started.html.erb
<%-cache do-%>
<section id="banner">
  <header>
    <h1>Tip any page on the Web</h1>
    <h4>It takes Three steps to get started.</h4>
    <p>The Copper Button lives on your browser's toolbar.
      It enables you to support the content you love
      online with a single click.</p>
  </header>
</section>

<section id="step_one">
  <header class='step'>1</header>
  <div>
    <h1>Sign up</h1>
    <a href="/auth/facebook">Login with Facebook</a>
    <p>Sign up by connecting yourFacebook account. </p>
    <p class="fine_print">Sign up using Google or Twitter coming soon.</p>
  </div>
</section>

<section id="step_two">
  <header class='step'>2</header>
  <div>
    <h1>Install the button</h1>
    <a class="button install">Install the button</a>
    <p class="chrome">
      The Copper Button lives on your browser’s
      toolbar. It enables you to support the content
      you love online with a single click.</p>
    <p class="safari">
      Clicking  “Get the Button” will download a file
      called copper.safariextz. It will appear in your
      Downloads folder. Open it and choose to install
      the extension.
    </p>
    <p class="mozilla">
      Click “Get the Button.” Confirm you want to add
      it by clicking “Allow.” Firefox will walk you
      through the last two steps.</p>
  </div>
  <figure>
    <%= image_tag "getting_started/chrome/magnification.png", class:"chrome" %>
    <%= image_tag "getting_started/safari/magnification.png", class:"safari" %>
    <%= image_tag "getting_started/firefox/magnification.png", class:"firefox" %>
  </figure>
</section>

<section id="step_three">
  <header class='step'>3</header>
  <div>
    <h1>Start Tipping</h1>
    <p>The Copper button should now be installed in
      the top Left corner of your browser. Add your
      credit card information and get started.</p>
    <p>All the cool kids are tipping with real money.</p>
    <p class="fine_print">Here’s the fine print: If you tip someone a buck,
      they get paid a buck. We charge you 10% for the
      service.</p>
  </div>
  <aside id='card'>
    <%= render partial:'shared/card' %>
  </aside>
</section>
<%-end-%>

app/views/home/index.html.erb
<%-cache current_user do-%>
  <section id="banner" itemscope itemtype="user" itemid="me">
    <header>
      <a href=/><img src="<%=current_user.authors.first.profile_image%>" class="author"></a>
    </header>
    <hgroup>
      <h1>what you love</h1>
      <p><%=current_user.name%><a href="/signout">not you?</a></p>
    </hgroup>
    <%-unless current_user.created_at < 7.days.ago-%>
    <p>
      This is your home on Copper. On this page, you track what
      you’ve tipped, change or cancel pending tips, and explore content made
      by your favorite creators.
    </p>
    <%-end-%>
  </section>
  <section id="stats" itemref="me">
    <header></header>
    <div>
      <h2>Pages tipped</h2>
      <p><%=current_user.tipped_pages.length%></p>
    </div>
    <div>
      <h2>Average tip</h2>
      <p data-cents='<%=current_user.tips.average(:amount_in_cents).round() if current_user.tips.count > 0%>'></p>
    </div>
    <div>
      <h2>Default tip</h2>
      <p>
        <span itemprop="tip_preference_in_cents" data-value="<%=current_user.tip_preference_in_cents%>"></span>
        <%= image_tag 'noun_project/5805.svg', alt:'increase default tip amount', class:'increase' %>
        <%= image_tag 'noun_project/5802.svg', alt:'decrease default tip amount', class:'decrease' %>
      </p>
    </div>
    <footer></footer>
  </section>

  <section class="pages" >
    <%-if current_user.pages.count > 0 -%>
      <%= render partial:"pages/current_user", collection:current_user.tipped_pages.endless(params[:endless]), as: :page %>
    <%-end-%>
  </section>

<%-end-%>

app/views/home/integrations.html.erb
<section id="banner">
  <header>
    <a href=/><%= image_tag "icons/silhouette.svg", class:"author", alt:'me' %></a>
  </header>
  <hgroup>
    <h1>pages</h1>
    <p><%=current_user.name%><a href="/signout">not you?</a></p>
  </hgroup>
  <details class='admin'>
    <summary><img width="2rem" height="2rem" class="admin" src='<%= image_path 'noun_project/8233.svg'%>'/></summary>
    <h3>admin</h3>
    <nav>
      <a href="/pages">pages</a>
      <a href="/authors">authors</a>
      <a href="/orders">orders</a>
      <a href="/users">users</a>
      <a href="/tips">tips</a>
      <a href="/checks">checks</a>
    </nav>
    <h3>services</h3>
    <nav>
      <a href="https://mixpanel.com/report/215574/funnels/#view/275542/from_date:-30,to_date:0" title="what up">Analytics</a>
      <a href="https://rpm.newrelic.com/accounts/331900/applications/2068138">performance</a>
      <a href="https://dashboard.heroku.com/apps/copper-production/resources">Heroku</a>
      <a href="https://manage.stripe.com/dashboard">stripe</a>
      <a href="https://www.copper.is/admin/resque/overview">resque</a>
  </details>
</section>
<section id="statistics">
  <figure>
    <%= image_tag "noun_project/2966.svg" %>
    <figcaption><%=User.count%> Fans</figcaption>
    <figcaption><b><%=User.where('created_at >= ?', Date.today.at_beginning_of_month).count%></b> this month</figcaption>
  </figure>
  <figure>
    <%= image_tag "noun_project/4060.svg" %>
    <figcaption><%=Tip.count%> Tips</figcaption>
    <figcaption><b><%=Tip.where('created_at >= ?', Date.today.at_beginning_of_month).count%></b> this month</figcaption>
  </figure>
  <figure>
    <%= image_tag "noun_project/4534.svg" %>
    <figcaption><%=Page.count%> Pages</figcaption>
    <figcaption><b><%=Page.where('created_at >= ?', Date.today.at_beginning_of_month).count%></b> this month</figcaption>
  </figure>
</section>

<section id='new_relic'>
  <figure>
    <iframe src="https://rpm.newrelic.com/public/charts/deCyaPDwlcU" width="100%" height="400" scrolling="no" frameborder="no"></iframe>
  </figure>
  <figure>
    <iframe src="https://rpm.newrelic.com/public/charts/4iBaBw0QfAA" width="100%" height="400" scrolling="no" frameborder="no"></iframe>
  </figure>
  <figure>
    <figcaption>Where people are coming from</figcaption>
    <iframe src="https://rpm.newrelic.com/public/charts/cZPpS1ZQuCc" width="500" height="300" scrolling="no" frameborder="no"></iframe>
  </figure>
</section>

app/views/home/settings.html.erb
<%-cache current_user do-%>
<section id="banner">
  <header>
    <a href=/><img src="<%=current_user.authors.first.profile_image%>" class="author"></a>
  </header>
  <hgroup>
    <h1>Your Settings</h1>
    <p><%=current_user.name%><a href="/signout">not you?</a></p>
  </hgroup>
  <%-unless current_user.stripe_id-%>
  <p>
    Hey, cool. You’ve found some great stuff to tip with Copper.
    Let’s get your tips to the creators...
    <br><br>
    Please add your payment info so we can start getting your
    tips to the people whose content you’ve liked. Once we have
    your info we’ll charge you weekly.
  </p>
  <%-end-%>
</section>

<section id="email" class="setting" itemscope itemtype="user" itemid="/users/<%=current_user.id%>">
  <header>
    <h2>Contact Info</h2>
    <a href="#">Change</a>
  </header>
  <div>
    <h4>Email Address</h4>
    <p itemprop="email"><%=current_user.email%></p>
  </div>
  <form method="put">
    <input itemprop="email" name='user[email]' type="email" required value="<%=current_user.email%>">
    <input type="submit" value="Save"/>
  </form>
</section>

<%= render partial:"shared/button"%>

<section id="sharing" itemref="/users/<%=current_user.id%>">
  <header>
    <h2>Facebook</h2>
  </header>
  <form action="/users/me" method="put">
    <input type='hidden' value='false' name="user[share_on_facebook]">
    <input itemprop="share_on_facebook" type="checkbox" name="user[share_on_facebook]" value="true" <%= "checked" if current_user.share_on_facebook? %>/>
    <label>Share tips on my timeline</label>
  </form>
</section>

<section id="rate" class="setting" itemref="/users/<%=current_user.id%>">
  <header>
    <h2>Default Tip</h2>
    <a href="#">Change</a>
  </header>
  <div>
    <p itemprop="tip_preference_in_cents"></p>
  </div>
  <form method="put">
    <select itemprop="tip_preference_in_cents" name="user[tip_preference_in_cents]">
      <option value="5" <%= 'selected ' if current_user.tip_preference_in_cents == 5%> >$0.05</option>
      <option value="10" <%= 'selected ' if current_user.tip_preference_in_cents == 10%>>$0.10</option>
      <option value="25" <%= 'selected ' if current_user.tip_preference_in_cents == 25%>>$0.25</option>
      <option value="50" <%= 'selected ' if current_user.tip_preference_in_cents == 50%>>$0.50</option>
      <option value="75" <%= 'selected ' if current_user.tip_preference_in_cents == 75%>>$0.75</option>
      <option value="100" <%= 'selected ' if current_user.tip_preference_in_cents == 100%>>$1.00</option>
      <option value="200"<%= 'selected ' if current_user.tip_preference_in_cents == 200%>>$2.00</option>
      <option value="300" <%= 'selected ' if current_user.tip_preference_in_cents == 300%>>$3.00</option>
      <option value="500" <%= 'selected ' if current_user.tip_preference_in_cents == 500%>>$5.00</option>
      <option value="1000" <%= 'selected ' if current_user.tip_preference_in_cents == 1000%>>$10.00</option>
      <option value="1500" <%= 'selected ' if current_user.tip_preference_in_cents == 1500%>>$15.00</option>
      <option value="2000" <%= 'selected ' if current_user.tip_preference_in_cents == 2000%>>$20.00</option>
    </select>
    <input type="submit" value="Save"/>
  </form>
</section>

<section id="card" class="setting" itemref="/users/<%=current_user.id%>">
  <header>
    <h2>Payment Info</h2>
    <a href="#card">Change</a>
  </header>
  <div>
    <section>
      <h4>Type Of Card</h4>
      <p class="type"></p>
    </section>
    <section>
      <h4>Card Number</h4>
      <p class="number"></p>
    </section>
    <section>
      <h4>Expiration</h4>
      <p class="expiration"></p>
    </section>
  </div>
  <%= render partial:'shared/card' %>
</section>

<section id="orders" class="setting" style='display:none;'>
  <header>
    <h2>Tip orders</h2>
  </header>
  <nav>
    <a href="/users/<%=current_user.id%>/orders">View order details</a>
  </nav>
</section>

<section id="address" class="setting" itemref="/users/<%=current_user.id%>">
  <header>
    <h2>Your address</h2>
    <a href="#address">Change</a>
  </header>
  <div>
    <p itemprop="payable_to"></p>
    <p itemprop="line1"></p>
    <p itemprop="line2"></p>
    <p>
      <span itemprop='city'></span>
      <span itemprop="subregion_code"></span>
      <span itemprop="postal_code"></span>
    </p>
  </div>
  <%= render partial:'shared/address' %>
</section>

<nav>
  <a href="/">return to profile</a>
</nav>
<%-end-%>

app/views/home/states.html.erb
<select name="user[subregion_code]" itemprop='subregion_code'>
  <option value="" disabled><%=@country.subregions.first.type%></option>
  <%-@country.subregions.each do |state|-%>
    <option value="<%=state.code%>"><%=state.name%></option>
  <%-end-%>
</select>

app/views/home/tipped.html.erb
<%-cache("homepage_pages", :expires_in => 1.minute) do-%>
<section class="pages">
  <%= render partial:"pages/as_figure", collection:Page.scott.limit(9), as: :page %>
</section>
<%-end-%>

app/views/home/weave.js.erb
(function(){
  var f = document.getElementById('weave');
  if (f) {
    console.debug("this shouldn't have happened. Iframes should be cleaned up.")
  }
  else {
    f=document.createElement('iframe');
    f.id='weave';
    f.frameborder=0;
    f.scrolling=0;
    f.target='weave';
    f.allowtransparency='allowtransparency';
    f.style.position='fixed';
    f.style.top='0';
    f.style.padding='0';
    f.style.zIndex='-1000';
    f.style.margin='0';
    f.style.border='none';
    f.style.left='0';
    f.style.background.color='transparent';
    f.scrolling='no';
    f.src='<%=request.scheme%>://<%=request.host%>:<%=request.port%>/bookmarklet/agent/#/' +
      window.location + '&title=' + document.getElementsByTagName('title')[0].innerHTML;
    document.body.appendChild(f);
    f.width='100%';
    f.height='100%';
    f.style.zIndex='1000';
    window.addEventListener('message',function(event) {
      // if (event.origin == '<%=request.scheme%>://<%=request.host%>:<%=request.port%>') {
        if (event.data == 'notify_complete') {
          var weave = document.getElementById('weave');
          document.body.removeChild(weave);
        }
      // }
    }, false);
  }
})()